import { Topic, Book, TrackId } from '@/types'

export const TRACK_META: Record<TrackId, { label: string; color: string; accent: string; icon: string; description: string; weeks: string }> = {
  devops:      { label: 'DevOps / SRE',      color: '#2563eb', accent: '#dbeafe', icon: '⚙', description: 'Linux → Docker → K8s → CI/CD → Observability → Cloud',  weeks: 'Starts week 3 · 24 weeks' },
  ai:          { label: 'AI / LLM',           color: '#7c3aed', accent: '#ede9fe', icon: '◈', description: 'LLM Zoomcamp 5-week sprint → Agents → Fine-tuning → MLOps', weeks: '5-week sprint now' },
  music:       { label: 'Guitar',             color: '#dc2626', accent: '#fee2e2', icon: '♩', description: 'Semi-acoustic → technique → theory → electric upgrade',       weeks: '30 min daily · 12+ months' },
  datascience: { label: 'Data Science / ML',  color: '#d97706', accent: '#fef3c7', icon: '∑', description: 'Math → Python DS → Classical ML → Deep Learning → MLOps',   weeks: 'Starts month 2 · 20 weeks' },
  web:         { label: 'Next.js / Nuxt / Node', color: '#db2777', accent: '#fce7f3', icon: '⌘', description: 'Next.js App Router → Node backend → Nuxt 3 → Edge deploy', weeks: 'Parallel · 20 weeks' },
  reading:     { label: 'Reading Culture',    color: '#059669', accent: '#d1fae5', icon: '◎', description: '1 book at a time · 20 pages/day · notes per chapter',          weeks: '1 book per month' },
}

export const TOPICS: Record<TrackId, Topic[]> = {
  devops: [
    { id: 'dv1',  title: 'Linux fundamentals',            description: 'Filesystem, processes, networking, bash scripting, systemd, cron', week: 'Wk 3–4',  tag: 'foundation', phase: 1 },
    { id: 'dv2',  title: 'Git advanced',                  description: 'Branching strategies, rebasing, hooks, monorepos, conventional commits', week: 'Wk 5', tag: 'foundation', phase: 1 },
    { id: 'dv3',  title: 'Docker & containerization',     description: 'Dockerfiles, compose, networking, volumes, multi-stage builds', week: 'Wk 6–7', tag: 'containers', phase: 1 },
    { id: 'dv4',  title: 'Kubernetes fundamentals',       description: 'Pods, deployments, services, ingress, config maps', week: 'Wk 8–9', tag: 'k8s', phase: 2 },
    { id: 'dv5',  title: 'Kubernetes advanced',           description: 'Helm, HPA, RBAC, network policies, production patterns', week: 'Wk 10–11', tag: 'k8s', phase: 2 },
    { id: 'dv6',  title: 'CI/CD pipelines',               description: 'GitHub Actions, ArgoCD, pipeline design, secrets management, GitOps', week: 'Wk 12–13', tag: 'automation', phase: 2 },
    { id: 'dv7',  title: 'Observability & SRE',           description: 'Prometheus, Grafana, Loki, SLIs/SLOs, alerting, incident response', week: 'Wk 14–16', tag: 'sre', phase: 3 },
    { id: 'dv8',  title: 'Terraform & IaC',               description: 'Infrastructure as code, modules, state management, workspaces', week: 'Wk 17–18', tag: 'iac', phase: 3 },
    { id: 'dv9',  title: 'Cloud — AWS/GCP',               description: 'IAM, VPC, compute, storage, managed K8s, cost optimization', week: 'Wk 19–22', tag: 'cloud', phase: 3 },
    { id: 'dv10', title: 'DevSecOps & capstone',          description: 'Secret scanning, policy-as-code, full deployment pipeline end-to-end', week: 'Wk 23–26', tag: 'capstone', phase: 3 },
  ],
  ai: [
    { id: 'ai0',  title: 'Module 0 — Setup & environment',        description: 'Course environment, Docker setup, API keys',                      week: 'Done',   tag: 'done', phase: 1 },
    { id: 'ai1',  title: 'Module 1 — Intro to LLMs & RAG',        description: 'What are LLMs, the RAG framework, first pipeline',                week: 'Wk 1',   tag: 'active', phase: 1 },
    { id: 'ai2',  title: 'Module 2 — Open-source LLMs',           description: 'Ollama, self-hosting, open-source alternatives to GPT',           week: 'Wk 2',   tag: 'soon', phase: 1 },
    { id: 'ai3',  title: 'Module 3 — Vector databases',           description: 'Semantic search, embeddings, Elasticsearch, Qdrant',              week: 'Wk 3',   tag: 'soon', phase: 1 },
    { id: 'ai4',  title: 'Module 4 — Evaluation & monitoring',    description: 'LLM-as-judge, offline evals, Grafana dashboards for LLM apps',    week: 'Wk 4',   tag: 'soon', phase: 1 },
    { id: 'ai5',  title: 'Module 5 — Capstone project',           description: 'End-to-end Q&A system on a knowledge base',                       week: 'Wk 5',   tag: 'soon', phase: 1 },
    { id: 'ai6',  title: 'Prompt engineering & chain-of-thought',  description: 'Systematic prompting, CoT, few-shot, structured outputs',         week: 'Wk 6',   tag: 'next', phase: 2 },
    { id: 'ai7',  title: 'Fine-tuning with LoRA / QLoRA',         description: 'Efficient fine-tuning, dataset prep, Hugging Face PEFT',          week: 'Wk 7–8', tag: 'next', phase: 2 },
    { id: 'ai8',  title: 'Agents & tool-use',                     description: 'ReAct, function calling, multi-step reasoning, LangGraph',         week: 'Wk 9–10', tag: 'next', phase: 2 },
    { id: 'ai9',  title: 'LLMOps — deployment & production',      description: 'Latency, cost, caching, API gateways, observability',             week: 'Wk 11–12', tag: 'next', phase: 2 },
    { id: 'ai10', title: 'Build & ship a personal AI project',    description: 'End-to-end AI product with monitoring and feedback loop',         week: 'Wk 13–14', tag: 'capstone', phase: 2 },
  ],
  music: [
    { id: 'mu1',  title: 'Open chord transitions — 60/min',     description: 'G, C, D, Em, Am smooth transitions with a metronome',            week: 'Daily',   tag: 'daily',     phase: 1 },
    { id: 'mu2',  title: 'Pentatonic scale — all 5 positions',  description: 'Major and minor pentatonic across the entire neck',               week: 'Wk 1–3',  tag: 'technique', phase: 1 },
    { id: 'mu3',  title: 'Fingerpicking — Travis & arpeggio',   description: 'Basic fingerpicking patterns, thumb independence',               week: 'Wk 2–4',  tag: 'technique', phase: 1 },
    { id: 'mu4',  title: 'Music theory — intervals & scales',   description: 'Major/minor scales, intervals, how chords are built',            week: 'Wk 1–6',  tag: 'theory',    phase: 1 },
    { id: 'mu5',  title: 'Rhythm — strumming with metronome',   description: 'Consistent strumming, 8th/16th note patterns, subdivision',     week: 'Daily',   tag: 'daily',     phase: 1 },
    { id: 'mu6',  title: 'Learn 4 songs end-to-end',            description: 'Choose songs you love, perform them clean',                      week: 'Monthly', tag: 'milestone', phase: 1 },
    { id: 'mu7',  title: 'Barre chords — all major & minor',    description: 'F barre, Bm, all E and A shape barre chords',                    week: 'Mo 4–5',  tag: 'technique', phase: 2 },
    { id: 'mu8',  title: 'CAGED system',                        description: 'Chord shapes across the full neck, connecting positions',        week: 'Mo 5–6',  tag: 'theory',    phase: 2 },
    { id: 'mu9',  title: 'Blues scale & improvisation',         description: 'Blues scale, call & response, improvising over a backing track', week: 'Mo 6–7',  tag: 'creative',  phase: 2 },
    { id: 'mu10', title: 'Rhythm — syncopation & muting',       description: 'Percussive muting, syncopated rhythms, dynamics',               week: 'Mo 7',    tag: 'rhythm',    phase: 2 },
    { id: 'mu11', title: 'Record monthly cover & self-critique',description: 'Video + audio recording, honest self-review',                   week: 'Monthly', tag: 'habit',     phase: 2 },
    { id: 'mu12', title: 'Modal playing — Dorian, Mixolydian',  description: 'Modes on the guitar, how they sound over chord progressions',   week: 'Mo 8–10', tag: 'advanced',  phase: 3 },
    { id: 'mu13', title: 'Solo transcription',                  description: 'Transcribe a solo by ear in your chosen style',                 week: 'Mo 10',   tag: 'advanced',  phase: 3 },
    { id: 'mu14', title: 'Fingerstyle full song arrangement',   description: 'Arrange a song with melody + harmony + bass simultaneously',    week: 'Mo 11',   tag: 'advanced',  phase: 3 },
    { id: 'mu15', title: 'Prepare for electric guitar upgrade', description: 'Research amps, cables, pedals, action setup — budget plan',     week: 'Mo 12',   tag: 'electric',  phase: 3 },
    { id: 'mu16', title: 'Electric — amp & tone setup',         description: 'EQ, gain staging, effects chain, amp sims',                     week: 'Yr 2',    tag: 'electric',  phase: 4 },
    { id: 'mu17', title: 'Electric — bending, vibrato, legato', description: 'Electric-specific techniques: bends, hammer-ons, pull-offs',    week: 'Yr 2',    tag: 'electric',  phase: 4 },
    { id: 'mu18', title: 'Lead playing vocabulary',             description: 'Blues, rock and jazz licks, building a solo vocabulary',        week: 'Yr 2',    tag: 'electric',  phase: 4 },
  ],
  datascience: [
    { id: 'ds1',  title: 'Math foundations',              description: 'Linear algebra, calculus (chain rule), probability, information theory', week: 'Wk 7–9',   tag: 'math',       phase: 1 },
    { id: 'ds2',  title: 'Python for data science',       description: 'NumPy, Pandas, Matplotlib, Seaborn, data cleaning, EDA',                week: 'Wk 10–11', tag: 'python',     phase: 1 },
    { id: 'ds3',  title: 'Classical ML — supervised',     description: 'Regression, classification, decision trees, SVMs, sklearn',             week: 'Wk 12–13', tag: 'ml',         phase: 2 },
    { id: 'ds4',  title: 'Classical ML — unsupervised',   description: 'Clustering, dimensionality reduction, PCA, anomaly detection',          week: 'Wk 14',    tag: 'ml',         phase: 2 },
    { id: 'ds5',  title: 'Model evaluation & pipelines',  description: 'Cross-validation, metrics, bias-variance, sklearn pipelines',           week: 'Wk 15',    tag: 'ml',         phase: 2 },
    { id: 'ds6',  title: 'Deep learning fundamentals',    description: 'Neural nets, backprop, PyTorch basics, training loops',                 week: 'Wk 16–17', tag: 'dl',         phase: 3 },
    { id: 'ds7',  title: 'CNNs & computer vision',        description: 'Convolutional networks, transfer learning, image classification',       week: 'Wk 18',    tag: 'dl',         phase: 3 },
    { id: 'ds8',  title: 'Transformers & NLP',            description: 'Attention mechanism, BERT, text classification, Hugging Face',          week: 'Wk 19–20', tag: 'dl',         phase: 3 },
    { id: 'ds9',  title: 'MLOps — experiment tracking',   description: 'MLflow, DVC, experiment reproducibility, model registry',              week: 'Wk 21–22', tag: 'mlops',      phase: 4 },
    { id: 'ds10', title: 'MLOps — model serving',         description: 'FastAPI serving, drift detection, feature stores, monitoring',         week: 'Wk 23–24', tag: 'mlops',      phase: 4 },
    { id: 'ds11', title: 'Capstone — end-to-end ML project', description: 'Data collection, modeling, deployment, monitoring in production',   week: 'Wk 25–26', tag: 'capstone',   phase: 4 },
  ],
  web: [
    { id: 'wb1',  title: 'Next.js App Router',            description: 'Layouts, loading states, error boundaries, route groups', week: 'Wk 1–2',  tag: 'nextjs',  phase: 1 },
    { id: 'wb2',  title: 'Server vs client components',   description: 'RSC mental model, boundaries, data fetching patterns',   week: 'Wk 2',    tag: 'nextjs',  phase: 1 },
    { id: 'wb3',  title: 'Server actions & mutations',    description: 'Form handling, revalidation, optimistic updates',        week: 'Wk 3',    tag: 'nextjs',  phase: 1 },
    { id: 'wb4',  title: 'Auth — NextAuth / Clerk',       description: 'Session management, OAuth, protected routes, middleware', week: 'Wk 4',    tag: 'nextjs',  phase: 1 },
    { id: 'wb5',  title: 'Build a full-stack Next.js app', description: 'SaaS with auth, DB, payments, deploy to Vercel',        week: 'Wk 5–7',  tag: 'project', phase: 1 },
    { id: 'wb6',  title: 'Node.js — REST API design',     description: 'Express / Fastify, routing, middleware, error handling', week: 'Wk 8–9',  tag: 'node',    phase: 2 },
    { id: 'wb7',  title: 'TypeScript in Node',            description: 'Types, decorators, dependency injection, strict mode',   week: 'Wk 9',    tag: 'node',    phase: 2 },
    { id: 'wb8',  title: 'Database — Prisma & Drizzle',   description: 'ORM patterns, migrations, relations, connection pooling', week: 'Wk 10',   tag: 'node',    phase: 2 },
    { id: 'wb9',  title: 'Testing — Vitest & Playwright', description: 'Unit, integration, E2E tests, CI integration',          week: 'Wk 11',   tag: 'node',    phase: 2 },
    { id: 'wb10', title: 'Nuxt 3 — composables',          description: 'Auto-imports, composables, Nuxt modules ecosystem',     week: 'Wk 12–13', tag: 'nuxt',   phase: 3 },
    { id: 'wb11', title: 'Nitro server & API routes',     description: 'Nuxt server routes, middleware, H3 framework',          week: 'Wk 13',   tag: 'nuxt',    phase: 3 },
    { id: 'wb12', title: 'Pinia + SSR hydration',         description: 'State management with SSR, hydration mismatches',       week: 'Wk 14',   tag: 'nuxt',    phase: 3 },
    { id: 'wb13', title: 'Deploy to edge — CF / Vercel',  description: 'Edge functions, CDN config, performance profiling',     week: 'Wk 15',   tag: 'deploy',  phase: 3 },
  ],
  reading: [],
}

export const BOOKS: Book[] = [
  {
    id: 'b1',
    title: '12 Rules for Life',
    author: 'Jordan B. Peterson',
    year: 2018,
    pages: 448,
    why: 'Antidote to chaos — Peterson\'s rules for personal responsibility and meaning. Pairs directly with building consistency across 6 tracks. Rule 1: stand up straight.',
    tags: ['self-mastery', 'philosophy', 'order'],
    color: '#059669',
    status: 'reading',
  },
  {
    id: 'b2',
    title: 'Emotional Intelligence',
    author: 'Daniel Goleman',
    year: 1995,
    pages: 352,
    why: 'Why IQ isn\'t enough — Goleman\'s landmark work on self-awareness, empathy, and managing emotions. Critical for leadership and sustaining long-term learning motivation.',
    tags: ['psychology', 'leadership', 'emotions'],
    color: '#2563eb',
    status: 'queued',
  },
  {
    id: 'b3',
    title: 'Deep Work',
    author: 'Cal Newport',
    year: 2016,
    pages: 296,
    why: 'Rules for focused success in a distracted world — directly applicable to managing 5 learning tracks. Newport\'s framework for producing at an elite level.',
    tags: ['productivity', 'focus', 'systems'],
    color: '#d97706',
    status: 'queued',
  },
  {
    id: 'b4',
    title: 'The Phoenix Project',
    author: 'Gene Kim, Kevin Behr, George Spafford',
    year: 2013,
    pages: 432,
    why: 'A novel about DevOps done right. The most painless way to absorb DevOps culture, deployment pipelines, and SRE thinking — reads like a thriller, not a textbook.',
    tags: ['devops', 'culture', 'systems thinking'],
    color: '#7c3aed',
    status: 'queued',
  },
  {
    id: 'b5',
    title: 'Atomic Habits',
    author: 'James Clear',
    year: 2018,
    pages: 320,
    why: 'The science of building and breaking habits — directly supports your 30-min guitar practice, daily learning streaks, and every consistency goal in this OS.',
    tags: ['habits', 'systems', 'behavior'],
    color: '#dc2626',
    status: 'queued',
  },
  {
    id: 'b6',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    year: 2017,
    pages: 616,
    why: 'The engineering bible for serious data work. Bridges your ML and DevOps tracks — covers databases, distributed systems, and reliability in one dense volume.',
    tags: ['engineering', 'data', 'distributed systems'],
    color: '#db2777',
    status: 'queued',
  },
]
