import { Topic, Book, TrackId } from '@/types'

export const TRACK_META: Record<TrackId, { label: string; color: string; accent: string; icon: string; description: string; weeks: string }> = {
  devops:      { label: 'DevOps / SRE',      color: '#2563eb', accent: '#dbeafe', icon: '⚙', description: 'Linux → Docker → K8s → CI/CD → Observability → Cloud',  weeks: 'Starts week 3 · 24 weeks' },
  ai:          { label: 'AI / LLM',           color: '#7c3aed', accent: '#ede9fe', icon: '◈', description: 'LLM Zoomcamp 5-week sprint → Agents → Fine-tuning → MLOps', weeks: '5-week sprint now' },
  music:       { label: 'Guitar',             color: '#dc2626', accent: '#fee2e2', icon: '♩', description: 'Semi-acoustic → technique → theory → electric upgrade',       weeks: '30 min daily · 12+ months' },
  datascience: { label: 'Data Science / ML',  color: '#d97706', accent: '#fef3c7', icon: '∑', description: 'Math → Python DS → Classical ML → Deep Learning → MLOps',   weeks: 'Starts month 2 · 20 weeks' },
  web:         { label: 'Next.js / Nuxt / Node', color: '#db2777', accent: '#fce7f3', icon: '⌘', description: 'Next.js App Router → Node backend → Nuxt 3 → Edge deploy', weeks: 'Parallel · 20 weeks' },
  reading:     { label: 'Reading Culture',    color: '#059669', accent: '#d1fae5', icon: '◎', description: '1 book at a time · 20 pages/day · notes per chapter',          weeks: '1 book per month' },
}

export const TOPICS: Record<TrackId, Topic[]> = {
  devops: [
    { id: 'dv1',  title: 'Linux fundamentals',            description: 'Filesystem, processes, networking, bash scripting, systemd, cron', week: 'Wk 3–4',   tag: 'foundation', phase: 1,
      subtopics: ['Filesystem hierarchy (FHS)', 'Permissions & ownership (chmod/chown)', 'Process management (ps, kill, top)', 'Bash scripting & control flow', 'SSH keys & config', 'systemd services & timers', 'Text tools: grep, awk, sed, cut', 'Networking: ip, ss, curl, netstat'] },
    { id: 'dv2',  title: 'Git advanced',                  description: 'Branching strategies, rebasing, hooks, monorepos, conventional commits', week: 'Wk 5', tag: 'foundation', phase: 1,
      subtopics: ['Branching strategies (Git Flow, trunk-based)', 'Interactive rebase & history cleanup', 'Git hooks (pre-commit, commit-msg)', 'Monorepo tooling (Nx, Turborepo)', 'Conventional commits & Commitizen', 'Cherry-pick, bisect, reflog', 'Submodules & subtrees'] },
    { id: 'dv3',  title: 'Docker & containerization',     description: 'Dockerfiles, compose, networking, volumes, multi-stage builds', week: 'Wk 6–7',  tag: 'containers', phase: 1,
      subtopics: ['Writing efficient Dockerfiles', 'docker-compose multi-service setup', 'Container networking (bridge, host, overlay)', 'Volumes & bind mounts', 'Multi-stage builds', 'Image optimization & layer caching', 'Docker Hub & private registries'] },
    { id: 'dv4',  title: 'Kubernetes fundamentals',       description: 'Pods, deployments, services, ingress, config maps', week: 'Wk 8–9',  tag: 'k8s', phase: 2,
      subtopics: ['Pods & containers', 'Deployments & ReplicaSets', 'Services (ClusterIP, NodePort, LoadBalancer)', 'Ingress controllers & TLS', 'ConfigMaps & Secrets', 'Namespaces & resource quotas', 'kubectl commands & YAML manifests'] },
    { id: 'dv5',  title: 'Kubernetes advanced',           description: 'Helm, HPA, RBAC, network policies, production patterns', week: 'Wk 10–11', tag: 'k8s', phase: 2,
      subtopics: ['Helm charts & templating', 'HPA & VPA autoscaling', 'RBAC roles & role bindings', 'Network policies', 'Persistent volumes & storage classes', 'Pod disruption budgets', 'Rolling updates & canary deployments'] },
    { id: 'dv6',  title: 'CI/CD pipelines',               description: 'GitHub Actions, ArgoCD, pipeline design, secrets management, GitOps', week: 'Wk 12–13', tag: 'automation', phase: 2,
      subtopics: ['GitHub Actions workflows & actions', 'ArgoCD & GitOps workflow', 'Build caching strategies', 'Secrets management (Vault, SOPS)', 'Deployment strategies (blue-green, canary)', 'Pipeline notifications & status checks', 'Docker image builds in CI'] },
    { id: 'dv7',  title: 'Observability & SRE',           description: 'Prometheus, Grafana, Loki, SLIs/SLOs, alerting, incident response', week: 'Wk 14–16', tag: 'sre', phase: 3,
      subtopics: ['Prometheus metrics & PromQL', 'Grafana dashboards & panels', 'Loki log aggregation & LogQL', 'SLI / SLO / error budget definition', 'Alerting rules & PagerDuty integration', 'Incident runbooks & postmortems', 'On-call best practices'] },
    { id: 'dv8',  title: 'Terraform & IaC',               description: 'Infrastructure as code, modules, state management, workspaces', week: 'Wk 17–18', tag: 'iac', phase: 3,
      subtopics: ['HCL syntax & resource blocks', 'Providers (AWS, GCP, Azure)', 'State files & remote backends', 'Modules & reusable components', 'Workspaces for multi-env', 'Terragrunt for DRY configs', 'Plan, apply, destroy workflow'] },
    { id: 'dv9',  title: 'Cloud — AWS/GCP',               description: 'IAM, VPC, compute, storage, managed K8s, cost optimization', week: 'Wk 19–22', tag: 'cloud', phase: 3,
      subtopics: ['IAM roles, policies & least privilege', 'VPC, subnets & security groups', 'EC2 / GCE compute & autoscaling', 'S3 / GCS object storage', 'RDS / CloudSQL managed databases', 'EKS / GKE managed Kubernetes', 'Cost optimization & reserved instances'] },
    { id: 'dv10', title: 'DevSecOps & capstone',          description: 'Secret scanning, policy-as-code, full deployment pipeline end-to-end', week: 'Wk 23–26', tag: 'capstone', phase: 3,
      subtopics: ['Secret scanning (TruffleHog, Gitleaks)', 'Policy-as-code with OPA / Gatekeeper', 'Container image scanning (Trivy)', 'SBOM generation', 'Shift-left security in pipelines', 'Full end-to-end deployment pipeline', 'Capstone: production-ready service'] },
  ],
  ai: [
    // ── PHASE 0: LLM Zoomcamp (already done) ────────────────────────────────
    { id: 'ai0', title: 'LLM Zoomcamp — RAG foundations (completed)', description: 'LLMs, RAG pipelines, vector search, evaluation, open-source models', week: 'Done ✓', tag: 'done', phase: 0,
      subtopics: [
        '✓ Module 0 — Environment setup, Docker, API keys',
        '✓ Module 1 — LLM & RAG intro: tokens, context window, first Q&A pipeline',
        '✓ Module 2 — Open-source LLMs: Ollama, LM Studio, quantization (GGUF)',
        '✓ Module 3 — Vector databases: embeddings, Elasticsearch, Qdrant, hybrid search',
        '✓ Module 4 — Evaluation: LLM-as-judge, hit rate, BERTScore, Grafana monitoring',
        '✓ Module 5 — Capstone: end-to-end RAG system on a personal knowledge base',
        'KEY INSIGHT: You know how to USE LLMs. Now you will understand HOW they work.',
      ],
    },

    // ── PHASE 1: Math & Python foundations ──────────────────────────────────
    { id: 'ai1', title: 'Math for AI — linear algebra', description: 'Vectors, matrices, dot products, eigenvalues — the language of AI', week: 'Wk 1–2', tag: 'math', phase: 1,
      subtopics: [
        'Scalars, vectors, matrices, tensors — what each represents in AI',
        'Vector operations — addition, scaling, dot product, angle between vectors',
        'Matrix multiplication — why it IS a neural network layer',
        'Transpose, inverse, identity matrix',
        'Eigenvalues & eigenvectors — intuition via stretching/rotation',
        'SVD (Singular Value Decomposition) — how PCA and attention tricks use it',
        'Norms — L1, L2, Frobenius — how we measure "size" in AI',
        'Resource: 3Blue1Brown "Essence of Linear Algebra" series (YouTube, free)',
        'Practice: implement matrix multiply from scratch in NumPy',
      ],
    },
    { id: 'ai2', title: 'Math for AI — calculus & optimization', description: 'Derivatives, chain rule, gradient descent — how models actually learn', week: 'Wk 2–3', tag: 'math', phase: 1,
      subtopics: [
        'Derivatives — rate of change, slope of a function',
        'Partial derivatives — changing one variable while others are fixed',
        'The gradient — direction of steepest ascent in multi-dim space',
        'Chain rule — how derivatives flow through composed functions (THIS is backprop)',
        'Gradient descent — moving opposite the gradient to minimize loss',
        'Learning rate — too big (diverge), too small (slow), just right',
        'Minima — local vs global, saddle points, flat regions',
        'Resource: 3Blue1Brown "Essence of Calculus" + Khan Academy',
        'Practice: implement gradient descent to minimize a simple function by hand',
      ],
    },
    { id: 'ai3', title: 'Math for AI — probability & statistics', description: 'Probability, distributions, Bayes theorem, information theory', week: 'Wk 3–4', tag: 'math', phase: 1,
      subtopics: [
        'Sample space, events, probability axioms',
        'Conditional probability — P(A|B), independence',
        'Bayes theorem — P(θ|data) ∝ P(data|θ)P(θ) — most important equation in ML',
        'Common distributions — Bernoulli, Gaussian, Categorical, Softmax output',
        'Expected value, variance, covariance',
        'Maximum Likelihood Estimation (MLE) — how we fit models to data',
        'Entropy — H(X) = -Σ p(x) log p(x) — measuring uncertainty',
        'Cross-entropy loss — why it is the natural loss for classification',
        'KL divergence — measuring distance between distributions (used in VAEs, RLHF)',
        'Resource: StatQuest with Josh Starmer (YouTube) — every video is gold',
      ],
    },
    { id: 'ai4', title: 'Python for AI', description: 'NumPy, vectorized ops, Matplotlib — the hands-on toolkit', week: 'Wk 4–5', tag: 'python', phase: 1,
      subtopics: [
        'Python fundamentals — list comprehensions, generators, decorators, type hints',
        'NumPy arrays — creation, shape, dtype, broadcasting rules',
        'NumPy vectorized operations — no loops needed, think in arrays',
        'Indexing & slicing — boolean masks, fancy indexing',
        'Linear algebra in NumPy — np.dot, np.matmul, np.linalg.*',
        'Matplotlib — plot, scatter, hist, imshow, subplots',
        'Jupyter notebooks — best practices, %timeit, %matplotlib inline',
        'Pandas basics for AI — loading datasets, EDA, train/test split',
        'Practice: implement a neural network forward pass using only NumPy',
        'Resource: fast.ai "Practical Deep Learning" chapter 1 (free)',
      ],
    },

    // ── PHASE 2: Classical ML ────────────────────────────────────────────────
    { id: 'ai5', title: 'Classical ML — core algorithms', description: 'Regression, classification, trees, SVMs — understanding learnable functions', week: 'Wk 5–7', tag: 'ml', phase: 2,
      subtopics: [
        'The ML framing — input features X, labels y, learn f: X → y',
        'Linear regression — OLS, gradient descent, L1/L2 regularization',
        'Logistic regression — sigmoid, binary cross-entropy, decision boundary',
        'Decision trees — information gain, Gini impurity, overfitting via depth',
        'Random forests — bagging, feature importance, why ensembles work',
        'Gradient boosting — XGBoost, LightGBM: additive models, trees as weak learners',
        'SVMs — max-margin hyperplane, kernel trick (polynomial, RBF)',
        'k-NN — lazy learning, curse of dimensionality',
        'Bias-variance tradeoff — the core tension in all of ML',
        'Sklearn — Pipeline, cross_val_score, GridSearchCV',
        'Practice: Kaggle Titanic or house price prediction end-to-end',
      ],
    },
    { id: 'ai6', title: 'Classical ML — evaluation & feature engineering', description: 'Metrics, cross-validation, feature transforms, SHAP', week: 'Wk 7', tag: 'ml', phase: 2,
      subtopics: [
        'Train / validation / test split — why three sets, not two',
        'k-fold cross-validation — reducing evaluation variance',
        'Classification metrics — accuracy, precision, recall, F1, ROC-AUC',
        'Regression metrics — MAE, RMSE, R², MAPE',
        'Confusion matrix — TP/FP/TN/FN, when each matters',
        'Feature engineering — log transforms, binning, interaction terms',
        'Handling missing data — imputation strategies',
        'Encoding categoricals — one-hot, ordinal, target encoding',
        'Feature selection — correlation filter, mutual information, RFECV',
        'SHAP values — model-agnostic explainability, waterfall plots',
        'Practice: full pipeline with feature engineering on a Kaggle dataset',
      ],
    },

    // ── PHASE 3: Neural Networks from scratch ────────────────────────────────
    { id: 'ai7', title: 'Neural networks — forward pass from scratch', description: 'Perceptrons, layers, activations, loss — build it with NumPy first', week: 'Wk 8–9', tag: 'neural-nets', phase: 3,
      subtopics: [
        'The perceptron — weights, bias, weighted sum, activation',
        'Why we need non-linearity — without it, deep = shallow',
        'Activation functions — Sigmoid, Tanh, ReLU, Leaky ReLU, GELU',
        'Multi-layer perceptron (MLP) — stacking layers',
        'Forward pass — computing activations layer by layer',
        'Loss functions — MSE (regression), cross-entropy (classification)',
        'Softmax — turning raw scores into probabilities',
        'Implement a 2-layer neural net forward pass using only NumPy',
        'Resource: Andrej Karpathy "Neural Networks: Zero to Hero" — lectures 1 & 2',
        'Practice: build a tiny MLP that classifies XOR',
      ],
    },
    { id: 'ai8', title: 'Neural networks — backpropagation', description: 'Computational graphs, chain rule, gradient flow — the engine of learning', week: 'Wk 9–10', tag: 'neural-nets', phase: 3,
      subtopics: [
        'Computational graphs — every operation is a node',
        'Local gradients — each node computes its own gradient',
        'Chain rule through graphs — upstream gradient × local gradient',
        'Backprop through addition, multiplication, ReLU, sigmoid',
        'Backprop through a full MLP layer-by-layer',
        'Vanishing gradient problem — why deep networks are hard to train',
        'Exploding gradients — gradient clipping',
        'Weight initialization — Xavier, He init — why random init matters',
        'Implement backprop from scratch in NumPy (no PyTorch yet)',
        'Resource: Karpathy "micrograd" — build a tiny autograd engine',
        'Practice: train your NumPy MLP on MNIST digits',
      ],
    },
    { id: 'ai9', title: 'PyTorch fundamentals', description: 'Tensors, autograd, nn.Module, training loops — the standard framework', week: 'Wk 10–11', tag: 'pytorch', phase: 3,
      subtopics: [
        'Tensors — creation, dtype, device (CPU/GPU), operations',
        'Autograd — requires_grad, .backward(), .grad, computational graph',
        'torch.no_grad() — inference mode, detach',
        'nn.Module — defining models, forward(), parameters()',
        'nn.Linear, nn.ReLU, nn.Sequential — building blocks',
        'Loss functions — nn.CrossEntropyLoss, nn.MSELoss',
        'Optimizers — SGD, Adam, AdamW — torch.optim',
        'The canonical training loop — zero_grad, forward, loss, backward, step',
        'Dataset and DataLoader — batching, shuffling, num_workers',
        'GPU training — .to(device), model.to(device)',
        'Saving/loading — state_dict, torch.save, torch.load',
        'Practice: reimplement MNIST classifier in PyTorch, compare to NumPy version',
      ],
    },
    { id: 'ai10', title: 'Convolutional neural networks (CNNs)', description: 'Convolution, pooling, feature maps, transfer learning for vision', week: 'Wk 11–12', tag: 'deep-learning', phase: 3,
      subtopics: [
        'Why convolutions — translation invariance, parameter sharing',
        'Convolution operation — filter, stride, padding, output size formula',
        'Feature maps — what each filter learns (edges → textures → objects)',
        'Pooling — max pool, average pool, reducing spatial dimensions',
        'CNN architecture pattern — [Conv → BN → ReLU → Pool] × N → FC',
        'Batch normalization — why it helps, train vs eval mode',
        'Dropout — regularization by random deactivation',
        'Famous architectures — LeNet → AlexNet → VGG → ResNet (residual connections)',
        'ResNet skip connections — solving vanishing gradients in deep nets',
        'Transfer learning — freeze pretrained backbone, train new head',
        'torchvision — ImageFolder, transforms, pretrained models',
        'Practice: fine-tune ResNet18 on a custom image dataset',
      ],
    },

    // ── PHASE 4: Sequence models & Attention ─────────────────────────────────
    { id: 'ai11', title: 'Recurrent networks & sequence modelling', description: 'RNNs, LSTMs, GRUs — learning from sequences before transformers', week: 'Wk 12–13', tag: 'deep-learning', phase: 4,
      subtopics: [
        'Why sequences are different — order matters, variable length',
        'Vanilla RNN — hidden state, unrolled computation, BPTT',
        'Vanishing gradient in RNNs — why long sequences break simple RNNs',
        'LSTM — forget gate, input gate, output gate, cell state',
        'GRU — simpler than LSTM, often comparable performance',
        'Bidirectional RNNs — reading sequence forward and backward',
        'Sequence-to-sequence — encoder/decoder for translation, summarisation',
        'Teacher forcing — training trick for seq2seq models',
        'Language modelling with LSTM — predicting next character/word',
        'Why transformers replaced RNNs — parallelism, long-range dependencies',
        'Practice: character-level language model (Shakespeare) with LSTM in PyTorch',
      ],
    },
    { id: 'ai12', title: 'Attention mechanism & Transformers', description: 'Self-attention, multi-head attention, positional encoding — the architecture behind GPT', week: 'Wk 13–15', tag: 'transformers', phase: 4,
      subtopics: [
        'The attention idea — which parts of the input should I focus on?',
        'Dot-product attention — Q, K, V matrices, score = QKt / sqrt(d)',
        'Softmax over scores — attention weights sum to 1',
        'Self-attention — Q, K, V all come from the same sequence',
        'Multi-head attention — parallel heads, different subspaces',
        'Positional encoding — sine/cosine or learned, injecting order',
        'Transformer encoder block — self-attention + FFN + layer norm + residual',
        'Transformer decoder block — masked self-attention + cross-attention',
        'Encoder-only (BERT) vs decoder-only (GPT) vs encoder-decoder (T5)',
        'Resource: "Attention Is All You Need" paper — read the original',
        'Resource: Karpathy "Let us build GPT from scratch" — implement it',
        'Practice: implement a mini GPT in PyTorch following Karpathy tutorial',
      ],
    },
    { id: 'ai13', title: 'Language models — BERT, GPT, and scaling', description: 'Pretraining objectives, tokenization, scaling laws, emergent abilities', week: 'Wk 15–16', tag: 'llm', phase: 4,
      subtopics: [
        'Tokenization deep dive — BPE, WordPiece, SentencePiece, tiktoken',
        'Pretraining — what it means to train on all of the internet',
        'BERT — masked language modelling (MLM), next sentence prediction (NSP)',
        'GPT family — autoregressive LM, causal masking, next token prediction',
        'Transfer learning in NLP — pretrain once, fine-tune everywhere',
        'Scaling laws — Chinchilla paper: model size × data × compute tradeoffs',
        'Emergent abilities — few-shot learning, chain-of-thought at scale',
        'RLHF — reinforcement learning from human feedback, reward models',
        'Constitutional AI / DPO — aligning models without RL',
        'Context window evolution — 4K to 1M tokens, why it matters',
        'Resource: Andrej Karpathy "Intro to Large Language Models" (YouTube)',
        'Practice: fine-tune DistilBERT for text classification on HuggingFace',
      ],
    },

    // ── PHASE 5: Applied modern AI ────────────────────────────────────────────
    { id: 'ai14', title: 'Prompt engineering & structured outputs', description: 'Systematic prompting, CoT, JSON mode — getting reliable outputs', week: 'Wk 16–17', tag: 'applied', phase: 5,
      subtopics: [
        'Why prompting matters even if you understand the internals',
        'System prompts — role, context, constraints, output format',
        'Zero-shot vs few-shot — when examples help most',
        'Chain-of-thought (CoT) — "think step by step", why it works',
        'Self-consistency — multiple CoT paths + majority vote',
        'Tree-of-thought — branching reasoning for complex problems',
        'Structured outputs — JSON mode, function calling, Pydantic + instructor',
        'Prompt injection — what it is, why it is hard to prevent',
        'DSPy — programmatic prompt optimization, not hand-crafting',
        'Practice: build a reliable structured data extractor using LLM + Pydantic',
      ],
    },
    { id: 'ai15', title: 'Fine-tuning & PEFT (LoRA / QLoRA)', description: 'When and how to fine-tune — efficient adaptation of large models', week: 'Wk 17–18', tag: 'applied', phase: 5,
      subtopics: [
        'When to fine-tune vs prompt engineer — cost, latency, privacy, quality',
        'Full fine-tuning — catastrophic forgetting, memory requirements',
        'PEFT — Parameter Efficient Fine-Tuning: adapt 0.1% of params',
        'LoRA — low-rank decomposition, rank r, target modules (Q, K, V)',
        'QLoRA — 4-bit quantized base + LoRA, fits on a single GPU',
        'Dataset formats — instruction tuning (Alpaca format), DPO pairs',
        'TRL SFTTrainer — Hugging Face training pipeline',
        'Evaluating fine-tuned models — perplexity, downstream benchmarks',
        'Merging adapters — LoRA merge back to base for inference',
        'Serving fine-tuned models — vLLM, Ollama with custom weights',
        'Practice: fine-tune Llama-3.2 3B on a custom instruction dataset with QLoRA',
      ],
    },
    { id: 'ai16', title: 'Agents & tool-use', description: 'ReAct, function calling, memory, multi-agent — LLMs that act in the world', week: 'Wk 18–19', tag: 'applied', phase: 5,
      subtopics: [
        'What is an agent — planning loop: observe, think, act, repeat',
        'ReAct pattern — interleaved Reasoning + Acting',
        'Function calling / tool use — JSON schema definitions, parallel calls',
        'Tools to build — web search, code interpreter, DB query, API calls',
        'LangGraph — stateful agent workflows, conditional edges, human-in-the-loop',
        'Memory architectures — in-context (window), external (vector), episodic',
        'Multi-agent patterns — supervisor, specialist agents, handoffs',
        'Agent reliability — retries, fallbacks, output validation',
        'Safety concerns — prompt injection into tools, sandboxing code exec',
        'Evals for agents — task completion rate, steps taken, cost per task',
        'Practice: build a research agent that searches, reads, and summarises papers',
      ],
    },
    { id: 'ai17', title: 'Advanced RAG — connecting back to Zoomcamp', description: 'Production RAG patterns now that you understand the internals', week: 'Wk 19–20', tag: 'applied', phase: 5,
      subtopics: [
        'Why your RAG from Zoomcamp will be 10x better now you understand embeddings',
        'Chunking strategies revisited — semantic chunking, late chunking',
        'Advanced retrieval — HyDE (hypothetical document embeddings), RAG fusion',
        'Reranking — cross-encoders, Cohere Rerank, ColBERT',
        'GraphRAG — knowledge graphs + vector search',
        'Agentic RAG — agent decides when to retrieve and what to query',
        'Multi-modal RAG — text + images (ColPali, vision models)',
        'Caching — semantic cache, prefix caching in vLLM',
        'Evaluation — RAGAS framework, LLM-as-judge at scale',
        'Production architecture — async indexing, streaming responses, observability',
        'Practice: rebuild your Zoomcamp RAG project with all new techniques',
      ],
    },
    { id: 'ai18', title: 'LLMOps & production AI systems', description: 'Serving, monitoring, cost control, safety — shipping AI that stays reliable', week: 'Wk 20–22', tag: 'mlops', phase: 5,
      subtopics: [
        'Inference serving — vLLM (PagedAttention), TGI, Ollama at scale',
        'Speculative decoding — draft model + verifier for 2-3x speedup',
        'Batching strategies — continuous batching, dynamic batching',
        'Quantization for production — AWQ, GPTQ, llama.cpp',
        'LLM gateway — LiteLLM: unified API, fallbacks, load balancing, cost tracking',
        'Observability — LangSmith, Langfuse: traces, evals, datasets',
        'Prompt versioning — managing prompt changes like code changes',
        'Guardrails — input/output validation, topic filters, PII redaction',
        'Cost optimisation — model routing by complexity, caching, batching',
        'Load testing — Locust for LLM APIs, realistic conversation patterns',
        'Practice: deploy a production RAG API with LiteLLM + Langfuse monitoring',
      ],
    },
    { id: 'ai19', title: 'Capstone — build an AI system from scratch', description: 'Design, train, deploy and monitor an AI product end-to-end', week: 'Wk 22–26', tag: 'capstone', phase: 5,
      subtopics: [
        'Choose a problem that genuinely interests you (not just a toy)',
        'Decide the right approach — RAG / fine-tune / agent / classifier',
        'Data collection and curation pipeline',
        'Training or fine-tuning with full experiment tracking (MLflow)',
        'Evaluation framework — offline metrics + LLM-as-judge + human review',
        'FastAPI backend with streaming, auth, rate limiting',
        'Next.js frontend (use your web track skills here)',
        'Deploy to cloud — containerised, with GPU if needed (Lambda Labs, RunPod)',
        'Production monitoring — Langfuse + Grafana dashboards',
        'Write a model card — capabilities, limitations, failure modes',
        'Share publicly — GitHub, blog post, or a demo video',
      ],
    },
  ],
  music: [
    { id: 'mu1',  title: 'Open chord transitions — 60/min',     description: 'G, C, D, Em, Am smooth transitions with a metronome',            week: 'Daily',   tag: 'daily',     phase: 1,
      subtopics: ['G → C → D transitions', 'Em → Am chord changes', '1-minute changes drill', 'Strumming while changing chords', 'Metronome at 60 BPM target', 'Tracking weekly BPM progress'] },
    { id: 'mu2',  title: 'Pentatonic scale — all 5 positions',  description: 'Major and minor pentatonic across the entire neck',               week: 'Wk 1–3',  tag: 'technique', phase: 1,
      subtopics: ['Minor pentatonic box 1 (position 1)', 'Positions 2 through 5', 'Connecting positions across the neck', 'String skipping exercises', 'Speed building with metronome', 'Major pentatonic patterns'] },
    { id: 'mu3',  title: 'Fingerpicking — Travis & arpeggio',   description: 'Basic fingerpicking patterns, thumb independence',               week: 'Wk 2–4',  tag: 'technique', phase: 1,
      subtopics: ['p-i-m-a finger assignment', 'Basic Travis picking pattern', 'Arpeggio up/down patterns', 'Thumb independence exercises', 'Combining fingerpicking with chord changes', 'Fingerpicking a full song section'] },
    { id: 'mu4',  title: 'Music theory — intervals & scales',   description: 'Major/minor scales, intervals, how chords are built',            week: 'Wk 1–6',  tag: 'theory',    phase: 1,
      subtopics: ['Half steps & whole steps', 'Major scale formula (W-W-H-W-W-W-H)', 'Intervals: 2nd through 7th', 'How major & minor triads are built', 'Key signatures & circle of 5ths', 'Chord function in a key (I IV V)'] },
    { id: 'mu5',  title: 'Rhythm — strumming with metronome',   description: 'Consistent strumming, 8th/16th note patterns, subdivision',     week: 'Daily',   tag: 'daily',     phase: 1,
      subtopics: ['Down-up strumming fundamentals', '8th note strumming patterns', '16th note patterns', 'Subdivision with metronome', 'Keeping time with a drum track', 'Dynamic control (soft vs loud)'] },
    { id: 'mu6',  title: 'Learn 4 songs end-to-end',            description: 'Choose songs you love, perform them clean',                      week: 'Monthly', tag: 'milestone', phase: 1,
      subtopics: ['Choosing songs you love & can finish', 'Chord & tab analysis', 'Slow section-by-section practice', 'Assembling full song run-through', 'Clean performance without stopping', 'Recording one for self-review'] },
    { id: 'mu7',  title: 'Barre chords — all major & minor',    description: 'F barre, Bm, all E and A shape barre chords',                    week: 'Mo 4–5',  tag: 'technique', phase: 2,
      subtopics: ['F major barre chord (E-shape)', 'All E-shape barre chords up the neck', 'A-shape barre chords', 'Bm chord', 'Muting unwanted strings', 'Finger strength & endurance building'] },
    { id: 'mu8',  title: 'CAGED system',                        description: 'Chord shapes across the full neck, connecting positions',        week: 'Mo 5–6',  tag: 'theory',    phase: 2,
      subtopics: ['C-A-G-E-D shapes on the fretboard', 'Connecting shapes across the neck', 'Seeing chord tones within each shape', 'Applying CAGED for soloing', 'Recognizing shapes in songs'] },
    { id: 'mu9',  title: 'Blues scale & improvisation',         description: 'Blues scale, call & response, improvising over a backing track', week: 'Mo 6–7',  tag: 'creative',  phase: 2,
      subtopics: ['Blues scale formula & fingering', 'Comparing minor pentatonic vs blues scale', 'Call & response phrasing concept', 'Practicing over a 12-bar blues track', 'Introduction to string bending', 'Beginner improv session recording'] },
    { id: 'mu10', title: 'Rhythm — syncopation & muting',       description: 'Percussive muting, syncopated rhythms, dynamics',               week: 'Mo 7',    tag: 'rhythm',    phase: 2,
      subtopics: ['Off-beat (syncopated) strumming', 'Percussive muting with right hand', 'Dynamic control in a song', 'Syncopated patterns in a groove', 'Funk-style muted strumming'] },
    { id: 'mu11', title: 'Record monthly cover & self-critique', description: 'Video + audio recording, honest self-review',                  week: 'Monthly', tag: 'habit',     phase: 2,
      subtopics: ['Recording setup (phone or audio interface)', 'Playing cleanly to a click track', 'Self-review checklist', 'Identifying weaknesses to practice', 'Optional: sharing for external feedback'] },
    { id: 'mu12', title: 'Modal playing — Dorian, Mixolydian',  description: 'Modes on the guitar, how they sound over chord progressions',   week: 'Mo 8–10', tag: 'advanced',  phase: 3,
      subtopics: ['How modes derive from the major scale', 'Dorian mode sound & feel', 'Mixolydian mode sound & feel', 'Playing modes over matching chord progressions', 'Songs that use Dorian / Mixolydian'] },
    { id: 'mu13', title: 'Solo transcription',                  description: 'Transcribe a solo by ear in your chosen style',                 week: 'Mo 10',   tag: 'advanced',  phase: 3,
      subtopics: ['Choosing a solo to transcribe', 'Slowing audio down by ear (Amazing Slow Downer)', 'Identifying each note', 'Writing it in tab or notation', 'Learning to play the transcribed solo', 'Analyzing phrasing & techniques used'] },
    { id: 'mu14', title: 'Fingerstyle full song arrangement',   description: 'Arrange a song with melody + harmony + bass simultaneously',    week: 'Mo 11',   tag: 'advanced',  phase: 3,
      subtopics: ['Melody + bass + harmony concept', 'Walking bass line technique', 'Chord melody introduction', 'Arranging section by section', 'Polishing to a complete performance'] },
    { id: 'mu15', title: 'Prepare for electric guitar upgrade', description: 'Research amps, cables, pedals, action setup — budget plan',     week: 'Mo 12',   tag: 'electric',  phase: 3,
      subtopics: ['Guitar body research (HSS vs HH vs semi-hollow)', 'Amp research (combo vs head + cab)', 'Essential pedals (overdrive, tuner, delay)', 'Cables & accessories checklist', 'Budget planning & timeline'] },
    { id: 'mu16', title: 'Electric — amp & tone setup',         description: 'EQ, gain staging, effects chain, amp sims',                     week: 'Yr 2',    tag: 'electric',  phase: 4,
      subtopics: ['Amp EQ settings (bass, mid, treble, presence)', 'Gain staging (clean vs overdrive)', 'Effects chain order (tuner → comp → OD → delay)', 'Amp sims (Neural DSP, Bias FX)', 'Recording direct into interface'] },
    { id: 'mu17', title: 'Electric — bending, vibrato, legato', description: 'Electric-specific techniques: bends, hammer-ons, pull-offs',    week: 'Yr 2',    tag: 'electric',  phase: 4,
      subtopics: ['Half-step & whole-step bends', 'Vibrato (finger vibrato vs wrist vibrato)', 'Hammer-ons technique & exercises', 'Pull-offs technique & exercises', 'Trills combining hammer-ons & pull-offs', 'Legato runs with clean notes'] },
    { id: 'mu18', title: 'Lead playing vocabulary',             description: 'Blues, rock and jazz licks, building a solo vocabulary',        week: 'Yr 2',    tag: 'electric',  phase: 4,
      subtopics: ['Minor pentatonic licks vocabulary', 'Blues turnaround phrases', 'Classic rock clichés & riffs', 'Jazz ii-V-I single-line phrasing', 'Building a solo from vocabulary pieces', 'Combining licks with dynamics'] },
  ],
  datascience: [
    { id: 'ds1',  title: 'Math foundations',              description: 'Linear algebra, calculus (chain rule), probability, information theory', week: 'Wk 7–9',   tag: 'math',     phase: 1,
      subtopics: ['Vectors, matrices & dot products', 'Matrix multiplication & inverse', 'Derivatives & the chain rule', 'Probability distributions (normal, Bernoulli, Poisson)', 'Bayes theorem & conditional probability', 'Entropy & KL divergence'] },
    { id: 'ds2',  title: 'Python for data science',       description: 'NumPy, Pandas, Matplotlib, Seaborn, data cleaning, EDA',                week: 'Wk 10–11', tag: 'python',   phase: 1,
      subtopics: ['NumPy arrays & broadcasting', 'Pandas DataFrames & Series', 'Matplotlib & Seaborn plotting', 'Data cleaning (nulls, dtypes, outliers)', 'EDA workflow & profiling', 'Jupyter notebook best practices'] },
    { id: 'ds3',  title: 'Classical ML — supervised',     description: 'Regression, classification, decision trees, SVMs, sklearn',             week: 'Wk 12–13', tag: 'ml',       phase: 2,
      subtopics: ['Linear & logistic regression', 'Decision trees & random forests', 'Support vector machines', 'sklearn API: fit / predict / transform', 'Feature engineering & selection', 'Gradient boosting (XGBoost, LightGBM)'] },
    { id: 'ds4',  title: 'Classical ML — unsupervised',   description: 'Clustering, dimensionality reduction, PCA, anomaly detection',          week: 'Wk 14',    tag: 'ml',       phase: 2,
      subtopics: ['k-means clustering', 'DBSCAN density-based clustering', 'PCA dimensionality reduction', 't-SNE & UMAP visualization', 'Isolation Forest for anomaly detection', 'Choosing k & elbow method'] },
    { id: 'ds5',  title: 'Model evaluation & pipelines',  description: 'Cross-validation, metrics, bias-variance, sklearn pipelines',           week: 'Wk 15',    tag: 'ml',       phase: 2,
      subtopics: ['Train / val / test split strategy', 'K-fold cross-validation', 'Metrics: precision, recall, F1, AUC-ROC', 'Bias-variance tradeoff visualization', 'Sklearn Pipelines & ColumnTransformer', 'Hyperparameter tuning (GridSearch, Optuna)'] },
    { id: 'ds6',  title: 'Deep learning fundamentals',    description: 'Neural nets, backprop, PyTorch basics, training loops',                 week: 'Wk 16–17', tag: 'dl',       phase: 3,
      subtopics: ['Perceptron & neural net basics', 'Forward pass & backpropagation', 'Activation functions (ReLU, sigmoid, tanh)', 'PyTorch tensors & autograd', 'Training loop (loss, optimizer, epochs)', 'GPU setup & cuda.is_available()'] },
    { id: 'ds7',  title: 'CNNs & computer vision',        description: 'Convolutional networks, transfer learning, image classification',       week: 'Wk 18',    tag: 'dl',       phase: 3,
      subtopics: ['Convolution & pooling operations', 'Classic CNN architectures (VGG, ResNet)', 'Transfer learning & fine-tuning', 'Image classification project end-to-end', 'Data augmentation strategies', 'torchvision transforms'] },
    { id: 'ds8',  title: 'Transformers & NLP',            description: 'Attention mechanism, BERT, text classification, Hugging Face',          week: 'Wk 19–20', tag: 'dl',       phase: 3,
      subtopics: ['Attention mechanism explained', 'Transformer architecture (encoder/decoder)', 'Tokenization (BPE, WordPiece)', 'BERT & RoBERTa fine-tuning', 'Text classification with HuggingFace', 'HuggingFace Trainer API'] },
    { id: 'ds9',  title: 'MLOps — experiment tracking',   description: 'MLflow, DVC, experiment reproducibility, model registry',              week: 'Wk 21–22', tag: 'mlops',    phase: 4,
      subtopics: ['MLflow experiment tracking setup', 'Logging params, metrics & artifacts', 'DVC for data & model versioning', 'Experiment reproducibility practices', 'Model registry & staging/production', 'Comparing runs across experiments'] },
    { id: 'ds10', title: 'MLOps — model serving',         description: 'FastAPI serving, drift detection, feature stores, monitoring',         week: 'Wk 23–24', tag: 'mlops',    phase: 4,
      subtopics: ['FastAPI model inference endpoint', 'Docker packaging for ML models', 'Data drift detection (Evidently)', 'Feature stores with Feast', 'Prometheus metrics for ML', 'Model monitoring dashboards'] },
    { id: 'ds11', title: 'Capstone — end-to-end ML project', description: 'Data collection, modeling, deployment, monitoring in production',   week: 'Wk 25–26', tag: 'capstone', phase: 4,
      subtopics: ['Problem definition & success metrics', 'Data collection & labeling pipeline', 'Modeling & experiment tracking', 'Deployment to cloud (GCP / AWS)', 'Online monitoring & alerting', 'Retraining trigger & loop'] },
  ],
  web: [
    { id: 'wb1',  title: 'Next.js App Router',            description: 'Layouts, loading states, error boundaries, route groups', week: 'Wk 1–2',  tag: 'nextjs',  phase: 1,
      subtopics: ['File-based routing in App Router', 'Layouts & nested layouts', 'loading.tsx & error.tsx conventions', 'Route groups with (folder)', 'Parallel routes & intercepting routes', 'Static vs dynamic rendering'] },
    { id: 'wb2',  title: 'Server vs client components',   description: 'RSC mental model, boundaries, data fetching patterns',   week: 'Wk 2',    tag: 'nextjs',  phase: 1,
      subtopics: ['"use client" directive & boundaries', 'RSC mental model & data fetching', 'Passing serializable props to client', 'Suspense boundaries for streaming', 'When to use each component type', 'Context in RSC architecture'] },
    { id: 'wb3',  title: 'Server actions & mutations',    description: 'Form handling, revalidation, optimistic updates',        week: 'Wk 3',    tag: 'nextjs',  phase: 1,
      subtopics: ['"use server" function declaration', 'Form handling with Server Actions', 'revalidatePath & revalidateTag', 'useOptimistic for instant UI updates', 'Progressive enhancement', 'Handling errors in Server Actions'] },
    { id: 'wb4',  title: 'Auth — NextAuth / Clerk',       description: 'Session management, OAuth, protected routes, middleware', week: 'Wk 4',    tag: 'nextjs',  phase: 1,
      subtopics: ['NextAuth.js installation & config', 'OAuth providers (GitHub, Google)', 'JWT vs database session strategy', 'Protecting routes with middleware', 'Auth in Server Components & Actions', 'Clerk as a drop-in alternative'] },
    { id: 'wb5',  title: 'Build a full-stack Next.js app', description: 'SaaS with auth, DB, payments, deploy to Vercel',        week: 'Wk 5–7',  tag: 'project', phase: 1,
      subtopics: ['Project scaffolding & planning', 'Prisma schema & DB setup', 'Auth integration (NextAuth / Clerk)', 'CRUD with Server Actions', 'Stripe payment integration', 'Deploy to Vercel with env vars'] },
    { id: 'wb6',  title: 'Node.js — REST API design',     description: 'Express / Fastify, routing, middleware, error handling', week: 'Wk 8–9',  tag: 'node',    phase: 2,
      subtopics: ['Express vs Fastify comparison', 'Router & controller structure', 'Middleware pipeline (logging, auth, errors)', 'Input validation with Zod', 'Error handling middleware', 'REST API design principles'] },
    { id: 'wb7',  title: 'TypeScript in Node',            description: 'Types, decorators, dependency injection, strict mode',   week: 'Wk 9',    tag: 'node',    phase: 2,
      subtopics: ['Strict tsconfig for Node', 'Type-safe request handlers', 'Generic types & utility types', 'Decorators & reflect-metadata', 'NestJS dependency injection basics', 'Module resolution & path aliases'] },
    { id: 'wb8',  title: 'Database — Prisma & Drizzle',   description: 'ORM patterns, migrations, relations, connection pooling', week: 'Wk 10',   tag: 'node',    phase: 2,
      subtopics: ['Prisma schema definition & types', 'Database migrations with prisma migrate', 'Relations: one-to-many, many-to-many', 'Drizzle ORM as an alternative', 'Connection pooling with pgBouncer', 'Optimizing slow queries'] },
    { id: 'wb9',  title: 'Testing — Vitest & Playwright', description: 'Unit, integration, E2E tests, CI integration',          week: 'Wk 11',   tag: 'node',    phase: 2,
      subtopics: ['Vitest unit tests setup', 'testing-library for React components', 'Mock service worker (MSW) for API mocking', 'Supertest for REST API testing', 'Playwright E2E test setup', 'CI test run in GitHub Actions'] },
    { id: 'wb10', title: 'Nuxt 3 — composables',          description: 'Auto-imports, composables, Nuxt modules ecosystem',     week: 'Wk 12–13', tag: 'nuxt',   phase: 3,
      subtopics: ['Auto-imports in Nuxt 3', 'useAsyncData & useFetch composables', 'Custom composables pattern', 'Nuxt modules ecosystem (Pinia, Auth)', 'Runtime config & environment variables', 'Nuxt DevTools'] },
    { id: 'wb11', title: 'Nitro server & API routes',     description: 'Nuxt server routes, middleware, H3 framework',          week: 'Wk 13',   tag: 'nuxt',    phase: 3,
      subtopics: ['server/api/ directory routes', 'H3 framework event handlers', 'Server-side middleware', 'Server-sent events (SSE)', 'Typed API responses with defineEventHandler', 'Error handling in Nitro'] },
    { id: 'wb12', title: 'Pinia + SSR hydration',         description: 'State management with SSR, hydration mismatches',       week: 'Wk 14',   tag: 'nuxt',    phase: 3,
      subtopics: ['Pinia store definition (Options & Setup API)', 'SSR hydration & useSSRRef', 'pinia-plugin-persistedstate', 'Avoiding hydration mismatches', 'Testing Pinia stores', 'Server-side data initialization'] },
    { id: 'wb13', title: 'Deploy to edge — CF / Vercel',  description: 'Edge functions, CDN config, performance profiling',     week: 'Wk 15',   tag: 'deploy',  phase: 3,
      subtopics: ['Vercel Edge Functions setup', 'Cloudflare Workers & KV storage', 'Edge middleware for auth & geo-routing', 'CDN cache-control headers', 'Core Web Vitals profiling', 'Bundle analysis & code splitting'] },
  ],
  reading: [],
}

export const BOOKS: Book[] = [
  {
    id: 'b1',
    title: '12 Rules for Life',
    author: 'Jordan B. Peterson',
    year: 2018,
    pages: 448,
    why: 'Antidote to chaos — Peterson\'s rules for personal responsibility and meaning. Pairs directly with building consistency across 6 tracks. Rule 1: stand up straight.',
    tags: ['self-mastery', 'philosophy', 'order'],
    color: '#059669',
    status: 'reading',
  },
  {
    id: 'b2',
    title: 'Emotional Intelligence',
    author: 'Daniel Goleman',
    year: 1995,
    pages: 352,
    why: 'Why IQ isn\'t enough — Goleman\'s landmark work on self-awareness, empathy, and managing emotions. Critical for leadership and sustaining long-term learning motivation.',
    tags: ['psychology', 'leadership', 'emotions'],
    color: '#2563eb',
    status: 'queued',
  },
  {
    id: 'b3',
    title: 'Deep Work',
    author: 'Cal Newport',
    year: 2016,
    pages: 296,
    why: 'Rules for focused success in a distracted world — directly applicable to managing 5 learning tracks. Newport\'s framework for producing at an elite level.',
    tags: ['productivity', 'focus', 'systems'],
    color: '#d97706',
    status: 'queued',
  },
  {
    id: 'b4',
    title: 'The Phoenix Project',
    author: 'Gene Kim, Kevin Behr, George Spafford',
    year: 2013,
    pages: 432,
    why: 'A novel about DevOps done right. The most painless way to absorb DevOps culture, deployment pipelines, and SRE thinking — reads like a thriller, not a textbook.',
    tags: ['devops', 'culture', 'systems thinking'],
    color: '#7c3aed',
    status: 'queued',
  },
  {
    id: 'b5',
    title: 'Atomic Habits',
    author: 'James Clear',
    year: 2018,
    pages: 320,
    why: 'The science of building and breaking habits — directly supports your 30-min guitar practice, daily learning streaks, and every consistency goal in this OS.',
    tags: ['habits', 'systems', 'behavior'],
    color: '#dc2626',
    status: 'queued',
  },
  {
    id: 'b6',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    year: 2017,
    pages: 616,
    why: 'The engineering bible for serious data work. Bridges your ML and DevOps tracks — covers databases, distributed systems, and reliability in one dense volume.',
    tags: ['engineering', 'data', 'distributed systems'],
    color: '#db2777',
    status: 'queued',
  },
]
